---
- name: Delete all data, and Docker
  hosts: all
  become: yes
  ignore_errors: yes

  tasks:
  - name: Check and Print LINUX system
    debug: var=ansible_distribution

  - name: Delete containers and Images
    shell: "{{ item }}"
    with_items:
          - docker stop $(docker ps -q)
          - docker rm $(docker ps -a -q)
          - docker rmi $(docker images -q)

  - block:  #==========Ubuntu=========
    - name: dellete
      shell: "{{ item }}"
      with_items:
          - dpkg -l | grep -i docker
          - apt-get purge -y docker-engine docker docker.io docker-ce
          - apt-get autoremove -y --purge docker-engine docker docker.io docker-ce
      
    when: ansible_distribution == "Ubuntu"

  - block:  #=========RedHat=========
    - name: delete
      shell: "{{ item }}"
      with_items:
          - yum remove -y docker-ce
          - rm -rd /var/lib/docker
    when: ansible_distribution == "RedHat"



#          - apt-get purge -y docker-engine docker docker.io docker-ce
#          - 
