
---
- name: Download and install Docker Image
  hosts: all
  become: yes
  ignore_errors: yes 
  
  tasks:
  - name: pull an image
    shell: "docker pull aleksefremov/efremov"

  - name: Check Containers
    shell: "docker ps -aq"
    register: resul
  
  - name: Delete containers
    shell: "{{ item }}"
    with_items:
        - docker stop $(docker ps -q)
        - docker rm $(docker ps -a -q)
    when: resul.stdout_lines[0] != "VARIABLE IS NOT DEFINED!"

  - name: Create Container
    shell: "docker run -d -p {{ item }}:80 aleksefremov/efremov"
    with_items: ['7777', '8888', '9999', '9998']

  - debug:
      var: resul.stdout_lines[0]
